DROP TABLE IF EXISTS temp_access;
DROP TABLE IF EXISTS users_sites;
DROP TABLE IF EXISTS sites;
DROP TABLE IF EXISTS users;
DROP PROCEDURE IF EXISTS get_password;
DROP PROCEDURE IF EXISTS get_uid;
DROP PROCEDURE IF EXISTS get_gid;
DROP PROCEDURE IF EXISTS get_dir;